name: Build et Packaging multi-plateformes

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    strategy:
      matrix:
        os: ubuntu-latest
        java-version: [ 21 ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout du code source
        uses: actions/checkout@v3

      - name: Configuration JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Clean du projet
        run: ./gradlew clean

      - name: Création du package avec jlink et jpackage
        run: ./gradlew jpackage

      - name: Récupération des packages
        uses: actions/upload-artifact@v4
        with:
          name: packages-${{ matrix.os }}
          path:
            build/jpackage/*
            build/distributions/*

  build-linux:
    strategy:
      matrix:
        os: windows-latest
        java-version: [ 21 ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout du code source
        uses: actions/checkout@v3

      - name: Configuration JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Vérification des droits d'exécution sur gradlew
        run: chmod +x gradlew

      - name: Clean du projet
        run: ./gradlew clean

      - name: Création du package avec jlink et jpackage
        run: ./gradlew jpackage

      - name: Récupération des packages
        uses: actions/upload-artifact@v4
        with:
          name: packages-${{ matrix.os }}
          path:
            build/jpackage/*
            build/distributions/*

  build-mac:
    strategy:
      matrix:
        os: macos-latest
        java-version: [ 21 ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout du code source
        uses: actions/checkout@v3

      - name: Configuration JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Vérification des droits d'exécution sur gradlew
        run: chmod +x gradlew

      - name: Clean du projet
        run: ./gradlew clean

      - name: Création du package avec jlink et jpackage
        run: ./gradlew jpackage

      - name: Récupération des packages
        uses: actions/upload-artifact@v4
        with:
          name: packages-${{ matrix.os }}
          path:
            build/jpackage/*
            build/distributions/*